<?php


$sampleFeaturedProducts = [
    [
        'id'           => 1,
        'name'         => 'Peacock Floral Wallpaper',
        'image'        => 'https://i.pinimg.com/736x/8b/07/2a/8b072a3f96b92dfe5203094f7cd3f938.jpg',
        'price'        => 7000,
        'color_name'   => 'Green',
        'color_hex'    => '#4E6B4E',
        'rating'       => 4.8,
        'review_count' => 32,
        'badge'        => 'Bestseller',
        'product_type' => 'wallpaper',
    ],
    [
        'id'           => 2,
        'name'         => 'Hexagon Floating Shelves',
        'image'        => 'hexagon.jpg',
        'price'        => 12500,
        'color_name'   => 'Black',
        'color_hex'    => '#2C1A0E',
        'rating'       => 4.6,
        'review_count' => 18,
        'badge'        => null,
        'product_type' => 'decor',
    ],
    [
        'id'           => 3,
        'name'         => 'Jute Pendant Lamp',
        'image'        => 'jute.jpg',
        'price'        => 11000,
        'color_name'   => 'Natural',
        'color_hex'    => '#997E67',
        'rating'       => 4.7,
        'review_count' => 24,
        'badge'        => 'Bestseller',
        'product_type' => 'decor',
    ],
    [
        'id'           => 4,
        'name'         => 'Wooden Wall Art Panel',
        'image'        => 'https://i.pinimg.com/1200x/00/79/1a/00791a9f30f4495f732df6634c65db86.jpg',
        'price'        => 27000,
        'color_name'   => 'Walnut',
        'color_hex'    => '#664930',
        'rating'       => 4.5,
        'review_count' => 11,
        'badge'        => null,
        'product_type' => 'decor',
    ],
    [
        'id'           => 5,
        'name'         => 'Bohemian Cushion Set',
        'image'        => 'https://i.pinimg.com/1200x/aa/44/05/aa4405d40a79c528682b8f660bacefc6.jpg',
        'price'        => 8500,
        'color_name'   => 'Terracotta',
        'color_hex'    => '#B44446',
        'rating'       => 4.4,
        'review_count' => 15,
        'badge'        => null,
        'product_type' => 'decor',
    ],
    [
        'id'           => 6,
        'name'         => 'Hand-Thrown Ceramic Vase',
        'image'        => 'https://i.pinimg.com/736x/eb/70/2a/eb702ab9a0d2e1a8aeaf1178444d318c.jpg',
        'price'        => 8500,
        'color_name'   => 'Blue & White',
        'color_hex'    => '#3B5A87',
        'rating'       => 4.9,
        'review_count' => 27,
        'badge'        => 'Bestseller',
        'product_type' => 'decor',
    ],
];
?>